### ISSUE TITLE
postgres id column data type

### ISSUE THREAD

**Issue by kane-mason** [thomas4019/expressa#130]
I know this is of my own doing, since i suggested there were benefits to using the `uuid` data type for the `id` column. One of the negatives is, that you **have to use a uuid**, which is not ideal for smaller tables where you want the document id to be something simple and readable. I still like the use of `uuid` by default, but wouldn't mind the flexibility to choose. Can you think of an elegant solution?

**Comment by thomas4019** [comment]
Hmm, I do like the ability to have custom ids for some tables and this is already being done for the `collection` and `role` collections. I'm thinking we could have an option on the collection called something like `useStringIds` which lets you use normal string ids instead of uuid for PostgreSQL or ObjectIDs for Mongo. What do you think?

**Comment by kane-mason** [comment]
I like that idea - not overthinking it and practical

**Comment by kane-mason** [comment]
This has been implemented
