### ISSUE TITLE
error responses as json

### ISSUE THREAD

**Issue by coderofsalvation** [thomas4019/expressa#25]
Expressa currently has a mixed policy when it comes to responding (results/errors in json or plain text).

I would opt for json-only responses, by creating an error function in `index.js` like this:

```
+ router.error = function(res,msg,code,info){
+  res.status(204).send({"error":msg, "code": code || 1,"info": info || ""}).end()
+ }

  router.use(>(req, res, next) {
·   req.settings = router.settings;
+   res.set('Content-Type','applicatioin/json'')
+   res.error = router.error
·   next()
  })
```

Now anywhere in the expressa code, or listeners, one could call `res.error("some error")` and the rest is taken care of.

Browser client-execution wouldn't crash on JSON parse-errors (in case of plaintext) or 404-statuses, they can recover appropriately by checking for the `error`-key in every response (and present a custom, more human errormessage based on the `code`-field)

WDYT?

**Comment by thomas4019** [comment]
I like the idea of always returning json and including an error key, code and message.

I'm unsure about adding the router.error function because it seems to be replacing the standard express error handling technique.
https://expressjs.com/en/guide/error-handling.html

Would this method let users catch errors and handle them differently if desired?

**Comment by coderofsalvation** [comment]
You're right, we would end up with 2 ways of handling errors.
How about this:

```
  router.use(>(req, res, next) {
·   req.settings = router.settings;
+   res.set('Content-Type','applicatioin/json'')
·   next()
  })

	var ExpressaError = (function(message,code,statuscode) {
                statuscode = statuscode || 204
		//handle constructor call without 'new'
		if (! (this instanceof ExpressaError)) return new ExpressaError(message);

		//populate error details
		this.code = code
                this.statuscode = statuscode
		this.message = message || ''	
		//include stack trace in error object
		Error.captureStackTrace(this, this.constructor);
	});

  router.delete('/:collection/:id', > (req, res, next) {
     // throw error instead of res.status.send()
     throw ExpressaError("could not find id",12)               
  })
  
  // Error handler, log and send to user
  router.use(>(err, req, res, next) {
  · console.log('expressa error:')
  · console.error(err.stack);
    var result = { error: err.message }
  · if ( req.hasPermission && req.hasPermission('view errors')) {                                                                                                                                                                                                                                                              
  · · result.code = err.code 
      result.stacktrace = err.stacktrace 
  · }
· · res.status( err.statuscode ).send(result)
  })
```

**Comment by thomas4019** [comment]
This is great! My thoughts would be to change the order of parameters to ExpressaError as below:
`var ExpressaError = (function(message, statuscode, code) {`

Since all users will see the statuscode, I think it is more important and then optionally another code could be provided which provides more details. Maybe this 3rd field could be called "details" instead of code?

Since this is an error, I think the default status code should be something 400+ instead of 204, maybe 500?

**Comment by coderofsalvation** [comment]
I like that. Lets use 500 as a default 'error'. 
I'll do a PR with it asap.

**Comment by thomas4019** [comment]
This change is implemented on master now. See ApiError which is based on your ExpressaError example.
