### ISSUE TITLE
What's the difference with Keystonejs?

### ISSUE THREAD

**Issue by muhajirframe** [thomas4019/expressa#49]
Hi, i am actually pretty new to backend world.

I just want to figure out what fits my need. So i am curious, is it the same as keystonejs or different?. I am looking for API-first / headless cms actually. Is expressa good choice for my case?
Thanks.

**Comment by thomas4019** [comment]
Hi,

Expressa is quite different from keystone.js. Keystone is much more developed, but also more complicated. If you're looking for a simple and extendable backend where your models are configured using JSON instead of code expressa would be a good choice. If you're looking for something with lots of features and a big community then Keystone would be better.
