### ISSUE TITLE
SQLite Support

### ISSUE THREAD

**Issue by am2064** [thomas4019/expressa#50]
Hello, 

I understand that the JSON file support offers a nice "on file database" solution, but I would like to propose offering SQLite support as well. JSON Files have a locking issue, and are limited by the file system. SQLite 3 offers most of the power of PostgreSql with the advantages of being lighter weight in every way. Along with offering a single easy to backup file as opposed to a complex database system that requires dedicated backup tools. SQLite is also a popular developer alternative to PostgresSql, as it allows the developer to reduce load on their machine while developing. 

SQLite recently added [support for json fields](https://sqlite.org/json1.html) which should allow for a fork of "mongo-query-to-postgres-jsonb" that turns it into "mongo-query-to-sqlite-json1".

**Comment by am2064** [comment]
Putting this as a reply as not to muddle the proposal post. I can try to fit in time in my schedule to add this functionality myself. I would need to know the requirements to have a pull request accepted.

**Comment by thomas4019** [comment]
Hi Antonio,
Thanks for this proposal! This sounds like a great addition to the project since it would give the same portability as the file db, but with a more scalable solution. Currently we're loose with pull requests, so as long as your db implementation works the same as the others (as much as possible), then there will be no problem adding it. I look forward to seeing this new feature :)

**Comment by thomas4019** [comment]
Closing as a stale issue. I'm definitely open to SQLite support and will review PRs, but I don't have need for it myself so it's not on the current roadmap.
