### ISSUE TITLE
fresh install: error on adding collection permissions

### ISSUE THREAD

**Issue by j2l** [thomas4019/expressa#64]
I installed expressa following readme and got an error after install:
```
error adding collection permissions

Error: could not load data

    at /rbd/pnpm-volume/db2e9f30-6bfe-4850-b75e-e887ea2d0f78/node_modules/.registry.npmjs.org/jfs/0.2.6/node_modules/jfs/lib/Store.js:209:15

    at ReadFileContext.callback (/rbd/pnpm-volume/db2e9f30-6bfe-4850-b75e-e887ea2d0f78/node_modules/.registry.npmjs.org/jfs/0.2.6/node_modules/jfs/lib/Store.js:94:16)

    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)

adding collection permissions for settings

adding collection permissions for collection

adding collection permissions for role

adding collection permissions for users

adding collection permissions for post
```
And this is the resulting admin UI I get:
![image](https://user-images.githubusercontent.com/65325/44912784-a1875500-ad2b-11e8-9e5e-8f0af6750b4d.png)

**Comment by thomas4019** [comment]
Thanks for reporting this issue. This error message is confusing, but the
server will actually work fine. Can you let me know if it's not working for
you.?

I'll investigate why it's printing out this error message and hope to
resolve it soon.

**Comment by j2l** [comment]
How can I create a new collection?
I don't have any option for that in the admin UI.

**Comment by thomas4019** [comment]
Hi, if you're running on port 80, then the collection creation and edit pages are hidden by default since it's safer not to enable that in a production environment. If you're only running locally or know you want editing in production you can setup the admin routes using the following code to always show option to create a new collection.

`app.use('/admin', expressa.admin({ apiurl: '/api/', showCriticalFeaturesOnProduction: true }));`

**Comment by j2l** [comment]
Thanks!
I now have "Add collection" button whick I didn't have before. You fixed it.
