### ISSUE TITLE
Unable to access /admin when expressa api set to anything other than '/api'

### ISSUE THREAD

**Issue by kane-mason** [thomas4019/expressa#86]
I want my expressa api to sit on the root of the server, everything seems to work except the /admin page is no longer accessible:

For example, running this:
```
var express = require('express');
var app = express();

var expressa = require('expressa');
app.use('/', expressa.api());            // optionally pass in settings
app.use('/admin', expressa.admin({ apiurl: '/' }));

app.listen(3000, function () {
    console.log('Example app listening on port 3000!');
});
```
then navigating to `http://localhost:3000/admin/`

results in the following error:

`{"error":"unknown collection"}`

**Comment by thomas4019** [comment]
Good catch! Two things are going on here 1) There's a regression where it seems the `apiurl` parameter no longer works since updating to the new Admin UI 2) You'd need to bring the line with '/admin' to be above '/'. Express uses the first possible match and so you want the most specific to be first.

I'll let you know when 1) is fixed and I'll also update the example in the Readme with the better ordering.
